#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 18 10:45:44 2017

@author: justinwu
"""
import numpy as np

a = np.arange(10)
print(a)
print('------------')
a = a.reshape((2,5))
print(a)
print('------------')
print(np.ravel(a))


